language: php

php:
  - 5.6

services:
  - redis-server

addons:
  apt:
    sources:
      - deadsnakes

    packages:
      - python2.6
      - python2.6-dev
      - nginx
      - realpath
      - lftp

# Separate different test suites
env:
  global:
    - PLUGIN_NAME=PlatformsReport
    - PIWIK_ROOT_DIR=$TRAVIS_BUILD_DIR/piwik
    - PIWIK_REPOSITORY_SLUG=PiwikPRO/piwik.git
    - PIWIK_LATEST_STABLE_TEST_TARGET=3.x-pro
    # github token
    - secure: "TELFOCCGK2dYbH5oKwC8It4pSsPcH7mIuxyt8LnbN56yQL7jx5RPWUHWSN8zlTWMU+J3HMGwf42WMZdwkLNGbzVB0tAKOAvfGZGISRJd2QNMbj/dVF2QfiVcJF3vGoI3b8H7lTwW0Hkacv/NmxTCrcZ/WAMcIbb5u5KM4jLjjwcb4//I/Sxgpy83TydR1uHwkG6MXWShNhsWWZmje8KyRqYne7150UlQ6Y9M3rg9JpLrJa0lBGZZFoxNLZXxtGgVJ4PL9dsTPkP+SIFklf2hpRiMiMnZXPaVkbU/f+Tx02R/+2smUEF+rnLMXICSQOVKsGmT5NMiCnl5/3osjV+fYKog/4hTsMQeCrj/J4Msmu+aYVw9M2KbDSaAPC+dtg4MvEdwGh2HlEVUCxGb5/2yUtfkADYa4Guuon3stAO+dRdCXhQzA53WpiTMJZ1z6f0PW14z99JE4hNiVobG76zeQ3U/sSfcfifSlAiIcQhAX6Suo/YrOmREm0YJzggvfj2454A1eMVDg31aqLfA8/VsWytg37BBavE7ybs6FuU91DtvEvAGPgd9asu5brBJ/gdzu5NmlTL3WNsgacM5eBpzUWgABeTeneK45vZq/2/2cMTd4EbMu5hDB3U35y7OXVe31eVYjQShGgguU+T3GOSBeAs7rxUt6bXpMLSCF6EO5OY="
    # artifacts pass
    - secure: "O+ejxvfQ/b10zY6C4qqqYA/lnpzqsklatNW2Xp3HP4YTpJVsIgzGdbjTuWR1s9JFR96EsiHx0L8DttqwewV/M/0RVvejV58ElpdGwDqzsZd1yweeIvi+fbPqfxmbexxAlRCaWa4LPuB5vbKPP9myNCDT60Wg/fx71EReHWI1zRtaxlOtzIuoakbyc0/GtFyHtyLjYTuhyuGma6AYr9iruPT1zppDPCCaRAnVj13q83o+BhxBIRIr8GwqKJwQpYNfO9/EV2kCA6pQyoznV9Yg21sNZVKAVzmY31wxSKY7cJsCH8s8+LIDN1QbLqvXIuJ7VkWq/WU8TY41mkqYdsdHpanzSJ40ec30xavJBuSlP6PvAMoWWg/7jK1IHWec8rg583VyLQa+1AogrEgFPgeNm173UEt8enMPPv/cJJrAEFaK1aYsx/wCKjeAN9XumTx2EiKIc4k7YNWiyg1Iepo2K+8BTWJsfEHXr7u0AMsEaxKybJeJjRkq2y0uQbwiH+QwnehdR4FGC5+nxTvy96+Y7ZngKBTjwaBQCj4cHEKDY7BwqNskX0Yfk2oaYhr3qfmvNYzRHkY+EkWmtMzyN3YpxgNf/2rBuzQMFUbRS8EuOCmovpd5/42tFGJtOBoDlKIZriIea2xxcQG9Oisqlc5W3ceQVU2u4rBfzAy/7NjFMHM="
  matrix:
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_LATEST_STABLE_TEST_TARGET
    # had to temporarily disable test for minimum_required_piwik because there is no 3.x tag on fork
    # - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_CORE=minimum_required_piwik
    # info from Cloud team: UI tests were removed from 3.x fork at the moment :(
    #- TEST_SUITE=UITests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_LATEST_STABLE_TEST_TARGET

sudo: required

script: $PIWIK_ROOT_DIR/tests/travis/travis.sh

before_install:

install:
  # move all contents of current repo (which contains the plugin) to a new directory
  - mkdir $PLUGIN_NAME
  - cp -R !($PLUGIN_NAME) $PLUGIN_NAME
  - cp -R .git/ $PLUGIN_NAME/
  - cp .travis.yml $PLUGIN_NAME
  # checkout piwik in the current directory
  - git clone -q https://$GITHUB_USER_TOKEN:@github.com/$PIWIK_REPOSITORY_SLUG piwik
  - cd piwik
  - git fetch -q --all
  - git submodule update --init -- tests/travis

  # make sure travis-scripts repo is latest for initial travis setup
  - '[ -d ./tests/travis/.git ] || sh -c "rm -rf ./tests/travis && git clone https://github.com/PiwikPRO/travis-scripts ./tests/travis"'
  - cd ./tests/travis ; git checkout master ; cd ../..

  - ./tests/travis/checkout_test_against_branch.sh

  - '[ "$PLUGIN_NAME" == "" ] || [ ! -f ./tests/travis/check_plugin_compatible_with_piwik.php ] || php ./tests/travis/check_plugin_compatible_with_piwik.php "$PLUGIN_NAME"'

  - ./tests/travis/configure_git.sh

  # travis now complains about this failing 9 times out of 10, so removing it
  #- travis_retry composer self-update
  - '[ "$SKIP_COMPOSER_INSTALL" == "1" ] || travis_retry composer install' 
 

  # move plugin contents to folder in the plugins subdirectory
  - rm -rf plugins/$PLUGIN_NAME
  - mv ../$PLUGIN_NAME plugins

  # clone dependent repos
  - ./tests/travis/checkout_dependent_plugins.sh

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-rm xdebug.ini; fi

  # add always_populate_raw_post_data=-1 to php.ini
  - echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # disable opcache to avoid random failures on travis
  - echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # make tmpfs and run MySQL on it for reasonnable performance
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo start mysql

  # print out mysql information
  - mysql --version
  - mysql -e "SELECT VERSION();"

  # configure mysql
  - mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'" # Travis default
  # try to avoid 'mysql has gone away' errors
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"

  - mysql -e "SELECT @@sql_mode;"
  # - mysql -e "SHOW GLOBAL VARIABLES;"

  # print out more debugging info
  - uname -a
  - date
  - php -r "var_dump(gd_info());"
  - mysql -e 'create database piwik_tests;'

  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - ./tests/travis/install_phantomjs.sh; export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH;

  - cd tests/PHPUnit

after_script:
  # change directory back to root travis dir
  - cd $PIWIK_ROOT_DIR

  # output contents of files w/ debugging info to screen
  - cat $PIWIK_ROOT_DIR/tests/travis/error.log
  - cat $PIWIK_ROOT_DIR/tmp/php-fpm.log
  - cat $PIWIK_ROOT_DIR/tmp/logs/piwik.log
  - cat $PIWIK_ROOT_DIR/config/config.ini.php

  # upload test artifacts (for debugging travis failures)
  - ./tests/travis/upload_artifacts.sh

after_success:
  - cd $PIWIK_ROOT_DIR
